name: Go Test with Atlas
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go 1.23
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      # Install dependencies
      - name: Install dependencies
        run: go mod download

      # Set up Atlas using the setup-atlas action
      - name: Setup Atlas
        uses: ariga/setup-atlas@v1

      # Run Go tests
      - name: Run tests
        run: go test ./...
